type: object
properties:
  deliverySettings:
    type: object
    description: Settings regarding how events should be delivered
    properties:
      url:
        type: string
        description: URL of the endpoint to be used for events delivery
      signing:
        type: object
        description: Parameters about signing
        properties:
          signatureHeader:
            type: string
            description: 'The HTTP header to be used for sending the signature of the delivery. Default: X-Pingwire-Signature'
            examples:
            - X-Pingwire-Signature
          timestampHeader:
            type: string
            description: 'The HTTP header to be used for sending the timestamp of the delivery. Default: X-Pingwire-Timestamp'
            examples:
            - X-Pingwire-Timestamp
      idempotencyHeader:
        type: string
        description: 'The HTTP header to be used for sending the idempotency key of the delivery. Default: Idempotency-Key'
        examples:
        - Idempotency-Key
      timeout:
        type: number
        description: 'Number of seconds to wait for the webhook endpoint to acknowledge the delivery. Default: 5s'
        maximum: 20
        minimum: 1
        examples:
        - 5
      retry:
        type: object
        description: Parameters of the retry logic
        properties:
          attempts:
            type: number
            description: 'Number of delivery attempts to be made for a single event before backing off. Default: 5'
            maximum: 10
            minimum: 1
            examples:
            - 5
          baseDelay:
            type: number
            description: 'Number of seconds used as the base delay between attempts. Default 5s'
            maximum: 900
            minimum: 1
            examples:
            - 5
          delayFactor:
            type: number
            description: 'Used to multiply the baseDelay for each attempt in order to achieve an exponential retry. Default: 2'
            maximum: 10
            minimum: 1
            examples:
            - 2
          jitterFactor:
            type: number
            description: 'Used to multiply the baseDelay to set the lower bound of the randomness. Use a value of 1 for no jitter and 0 for full jitter. Default: 0.75'
            minimum: 0
            maximum: 1
            examples:
            - 0.75
